helm-extra-args: --timeout 600s
check-version-increment: false
debug: true
chart-dirs:
  - helm
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
charts: [ "helm/ditto-operator" ] # need to prefix with "helm/"