[package]
name = "ditto-operator"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]

kube = "0.35.1"
kube-derive = "0.35.1"
k8s-openapi = { version = "0.8.0", default-features = false, features = ["v1_17"] }
openshift-openapi = { version = "0.0.1", default-features = false, features = ["v4_4"] }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"

tokio = { version = "0.2", features = ["full"] }

futures-util = "0.3"
futures = "0.3"
anyhow = "1.0"

async-trait = "0.1"
async-std = "1.5"

percent-encoding = "2.1.0"

log = "0.4"
env_logger = "0.7"
rand = "0.7"
sha1 = "0.6"
operator-framework = { version = "0.1.5", features = [ "v1_17" ] }

string-error = "0.1.0"

[patch.crates-io]
#k8s-openapi = { git = "https://github.com/Arnavion/k8s-openapi.git#b8046d9a" }
#kube-derive = { git = "https://github.com/ctron/kube-rs", branch="feature/meta_mut_1" }
#operator-framework = { path = "/home/jreimann/git/operator-framework" }
