[package]
name = "ditto-operator"
version = "0.3.1"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "EPL-2.0"

[dependencies]

kube = "0.51"
kube-derive = "0.51"
kube-runtime = "0.51"
snafu = "0.6"

k8s-openapi = { version = "0.11", default-features = false }
openshift-openapi = { version = "0.3", default-features = false, features = ["v4_4"] }

tokio = { version = "1", features = ["full"] }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"

futures-util = "0.3"
futures = "0.3"
anyhow = "1"

async-trait = "0.1"
#async-std = "1.5"

percent-encoding = "2"

log = "0.4"
env_logger = "0.7"
rand = "0.7"
sha1 = "0.6"
operator-framework = { version = "0.5", features = ["v1_17"] }

string-error = "0.1.0"

[patch.crates-io]
#k8s-openapi = { git = "https://github.com/Arnavion/k8s-openapi.git#b8046d9a" }
#kube = { git = "https://github.com/clux/kube-rs", branch="master" }
#kube-derive = { git = "https://github.com/clux/kube-rs", branch="master" }
#operator-framework = { path = "../operator-framework" }
kube = { git = "https://github.com/ctron/kube-rs", rev = "59f175adc61575b83c01fc8809ea70cb7c172ebb" }
operator-framework = { git = "https://github.com/ctron/operator-framework", rev = "e827775e023dfbe22a9defbf31e6a87f46d38ef5" }
