[package]
name = "ditto-operator"
version = "0.1.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"

[dependencies]

kube = "0.35.0"
kube-derive = "0.35.0"
k8s-openapi = { version = "0.8.0", default-features = false, features = ["v1_17"] }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"

tokio = { version = "0.2", features = ["full"] }

futures-util = "0.3"
futures = "0.3"
anyhow = "1.0"

async-trait = "0.1"
async-std = "1.5"

log = "0.4"
env_logger = "0.7"
rand = "0.7"
sha1 = "0.6"
operator-framework = { version = "0.1.1", features = [ "patched", "v1_17" ] }

[patch.crates-io]
k8s-openapi = { git = "https://github.com/Arnavion/k8s-openapi.git#b8046d9a" }

kube = { path = "kube-rs/kube" }
kube-derive = { git = "https://github.com/ctron/kube-rs", branch="feature/meta_mut_1" }

operator-framework = { git = "https://github.com/ctron/operator-framework" }
