replicaCount: 1

image:
  repository: docker.io/ctron/ditto-operator
  # tag: # defaults to the app version
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name:

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  enabled: true
