---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi8
spec:
  tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8
      name: latest
      importPolicy:
        scheduled: true
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubi8-minimal
spec:
  tags:
    - from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi8-minimal
      name: latest
      importPolicy:
        scheduled: true
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ditto-operator
spec: {}