---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ditto-operator
spec:
  triggers:
    - type: ImageChange
  source:
    git:
      uri: https://github.com/ctron/ditto-operator
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8:latest
  output:
    to:
      kind: ImageStreamTag
      name: ditto-operator:latest
