kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ditto-operator
  labels:
    app.kubernetes.io/name: ditto-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "services", "configmaps", "secrets", "serviceaccounts"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments" ]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
  - apiGroups: ["iot.eclipse.org"]
    resources: ["dittos", "dittos/status", "dittos/finalizers"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
