apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ditto-operator.fullname" . }}
  labels:
    {{- include "ditto-operator.labels" . | nindent 4 }}
  {{- if .Values.s2i.enabled }}
  annotations:
    image.openshift.io/triggers: |
      [
        {
          "from": {
            "kind":"ImageStreamTag",
            "name":"{{ include "ditto-operator.fullname" . }}:latest"
          },
          "fieldPath":"spec.template.spec.containers[?(@.name==\"operator\")].image"
        }
      ]
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ditto-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ditto-operator.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ditto-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.s2i.enabled }}
          image: {{ include "ditto-operator.fullname" . }}
          {{- else }}
          image: {{ .Values.image.repository }}:{{ include "ditto-operator.imageTag" . }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: HAS_OPENSHIFT
              value: {{ .Values.openshift.enabled | quote }}
            - name: RUST_LOG
              value: info
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
