---
{{- if .Values.rbac.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ditto-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ditto-operator.name" . }}
{{ include "ditto-operator.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "services", "configmaps", "secrets"]
    verbs: ["create", "update", "delete", "get", "watch", "list"]
{{- end -}}
